#!/bin/bash

#SBATCH --partition=gpu_a100            # Use GPU partition
#SBATCH --gpus=1                        # Request 1 GPU
#SBATCH --job-name=cross_validate    # Job name
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12             # Adjust CPU usage if needed
#SBATCH --time=4:00:00                # Max time
#SBATCH --output=slurm_outputs/cross_validate_%A.out  # Save output logs

# Load necessary modules
module purge
module load 2023
module load Anaconda3/2023.07-2

# Change to the project directory
cd /home/mvanderbrugge/photoacoustic-image-quality-assessment

# Activate the virtual environment
source activate photoacoustic-env

# Set PYTHONPATH so src is treated as module root
export PYTHONPATH=src

# Check GPU availability
echo "Checking whether the GPU is available"
srun python -uc "import torch; print('GPU available?', torch.cuda.is_available())"

# Run training for all metrics
echo "Starting cross validate..."
srun python src/dl_model/cross_validate.py --csv_path results/denoising_data/denoising_data_per_image_metrics_2025-05-06_11-18-30.csv --metric SSIM